site:
  title: Eclipse GlassFish Documentation
  url: https://omnifish-ee.github.io/glassfish-documentation
  start_page: glassfish::ROOT:index.adoc

urls:
  # The latest stable version uses the segment "latest" in its URL
  # e.g. /glassfish/latest/index.html always points to the current stable release
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:to

content:
  sources:
    - url: ./antora-content
      start_path: 8.0-SNAPSHOT
      branches: HEAD
    - url: ./antora-content
      start_path: 8.0.3
      branches: HEAD
    - url: ./antora-content
      start_path: 7.1.1
      branches: HEAD
    - url: ./antora-content
      start_path: 7.0.26
      branches: HEAD

ui:
  bundle:
    url: ./antora-ui-default.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

asciidoc:
  attributes:
    source-highlighter: highlight.js
    icons: font
    sectanchors: ''
    idprefix: ''
    idseparator: '-'
    toc: ''
    toclevels: 3

antora:
  extensions:
    - require: '@antora/lunr-extension'
